branches:
  only:
  - master
  - develop
dist: xenial
language: python
python:
- '3.7'
before_install:
- mkdir ./.msiem
#- openssl aes-256-cbc -K $encrypted_59847529a656_key -iv $encrypted_59847529a656_iv -in ./tests/conf-test.ini.enc -out ./.msiem/conf.ini -d
install:
- python3 ./setup.py install
- pip3 install -r requirements.txt
script:
#- python3 -m unittest tests.auth.test_session
#- python3 ./setup.py test
- python3 -m unittest tests.local.test_base
- git clone https://github.com/mfesiem/mfesiem.github.io
- pdoc3 msiempy --output-dir ./mfesiem.github.io/docs --html --force

#- pyreverse -s 1 -f PUB_ONLY -o png -m y msiempy
#- mv ./classes.png ./mfesiem.github.io/docs/msiempy
#- mv ./packages.png ./mfesiem.github.io/docs/msiempy
after_success:
  env:
    global:
      secure: DIfIi6vcboKx/h72e4B+ENz63uolupopVsAA7ipl/SSMXkR0XIm5y2gfBIObzaGCm6x9AzYT7H9QNMjeGugEa8ij12KbdRIV+b8k+K/pF5zwuEW3slsFu/oGjYSIg4yl72BNkEQVVVvLH/ANr7wkVUQXiH/Ei0gdL2DpYoCy+QxSRqo0sBF2LCc4ZVODwhkcJn+7KB8/bgpnqd+amx4iJUiKRE6a2NvyqE+K+qgoAJYKZeYdxfzcn7ExC3MIKv7K/+s56KA+OFMYdjg2RhlYeUAj2m+CoOsh/vt+f32+QRrcBVWj5lPNJG3v2FVN6wu3TAIeQ52FBfFhNCkQrKVmx9sR7ziB7fifG3hqx1Mf+uiC/ao1gqsB+bnOxyNQfkpQCk/ay325UydGxgGxBaaobjzoFq7UnnCBTpfB8rurB2p9aajVNwiZ1PwJr+NAZG8fEL8CyRiizYDDE4x8kN2WuFLfTzJYzguklohmBukk1M/8JKqJaPh5Waas4gkYMdVcweAjw6+PcrGD7VBX2ETCiAC2hrmxUpYo6rhdWAVPZvlatjJV4KqMInRcGsRccl1fLQ14UfbkbuiSPnxy4r/jYKnDA2Ya38Qq2pT19ECBnDfvP6buiyEcNxc3oUmnv45dVOBLnR38uv5D2mfYqkcYiRjov8tW83i9B+uI9u7uFdo=
  script:
  - cd mfesiem.github.io
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git remote add autodoc https://${GH_TOKEN}@github.com/mfesiem/msiempy.git
  - git add .
  - git commit -m "Generate docs $(date)"
  - git push autodoc master --set-upstream autodoc master
  - cd ..
  - rm -rf mfesiem.github.io
  deploy:
    provider: pypi
    user: tristanlatr
    password:
      secure: WHIvn8Ize/hprEW+TmNcx/elZI9rSRExKTgdooimNLY5VKP6b1rzGSd3SDei7mwsArAx5GARQK/D8pah3+avKQ1+LrEm3CVPiAEm70vLkuwb/FaiCcJSOwMJ38ZMd3QZ+atTa/SZm3nxHUij675BsRTdLWonRIHDSnS3HUtoj0igjCC2UB9uaqTZPU8Ev7DBc7mfXLfNPVmZFCS3En4fypyZZjB+BnKqV2EnVipJz5V1t5xuAqbR+roGYlRYGTle7oIvBJ+UEdwt+dL/McQgbdubzTNlKMYdroqpUt0jdICr6YDhvqIXWIdtqgrf0zgCfM3GAA+/RsyIU91fhLGqfnMPtINS841QG5K/8W/BOp0LueSpu2lkoDns86Xv4hKNVdYc7p3pw77gxJzrI91k/QUg5yn5PTjufJDrVPb8cQ6U6Z/ZRDvIlkHXjDLiUqJWBThaFPdwnNFAq6qmEhbGx08w8uQQHEi58WaLM5dBHfrlLAKStm4XEX7ydZa/ODFeTE+yOAdysgRj3g2x+arI1f5pUZHHTkNiocStmy4ZWzN8c7KWdjNd5aBWNoT5Gg7x1kWMTijYTJb92pEwFii2+yGmikbdq5gD6AgiJ6bW3CWva6ARgzs5VsGack+oMQm/drBIttTMEw3tP5NJu1sbdKuDXw1RYJkOh4LaWTzaSqA=
    on:
      tags: true
  after_deploy:
    script:
    - pip3 install msiempy --upgrade
